# Generated by Django 2.1.1 on 2018-10-26 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 12, 1, 7, 138627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='end1',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 11, 1, 7, 139502, tzinfo=utc)),
        ),
    ]
