# Generated by Django 2.1.1 on 2018-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
