# Generated by Django 2.1.1 on 2018-11-05 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 8, 10, 1, 453858, tzinfo=utc)),
        ),
    ]
