# Generated by Django 2.1.1 on 2018-09-25 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.date(2018, 9, 26)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 25, 16, 28, 25, 698188, tzinfo=utc), null=True),
        ),
    ]
