# Generated by Django 2.1.1 on 2018-10-01 04:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 2, 4, 34, 4, 376756, tzinfo=utc)),
        ),
    ]
