# Generated by Django 2.1.1 on 2018-10-30 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 14, 57, 2, 607759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent_time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent_time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
