# Generated by Django 2.1.4 on 2019-03-02 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 2, 20, 51, 28, 642431, tzinfo=utc)),
        ),
    ]
