# Generated by Django 2.1.1 on 2018-09-26 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 10, 34, 57, 582566, tzinfo=utc), null=True),
        ),
    ]
