# Generated by Django 2.1.1 on 2018-09-19 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 8, 31, 47, 32320, tzinfo=utc), null=True),
        ),
    ]
