# Generated by Django 2.1.1 on 2018-10-25 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('start1', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end1', models.DateTimeField(default=datetime.datetime(2018, 10, 30, 18, 22, 0, 242747, tzinfo=utc))),
                ('fine', models.IntegerField(default=0)),
                ('rent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_rent', to=settings.AUTH_USER_MODEL)),
                ('seller1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_seller1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='visa',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Grocery', 'Grocery'), ('Mobiles', 'Mobiles'), ('Clothes', 'Clothes'), ('Electronics', 'Electronics'), ('Home Appliances', 'Home appliances'), ('Beauty', 'Beauty'), ('Toys', 'Toys'), ('Sports', 'Sports'), ('Footwear', 'Footwear'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 19, 22, 0, 242747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Visa',
        ),
    ]
