# Generated by Django 2.1.1 on 2018-09-26 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180926_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 16, 48, 37, 742983, tzinfo=utc)),
        ),
    ]
