# Generated by Django 2.1.1 on 2018-10-26 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181026_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='end1',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rent_id',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='seller1',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='start1',
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 20, 49, 0, 261010, tzinfo=utc)),
        ),
    ]
