# Generated by Django 2.1.1 on 2018-09-29 05:30

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180926_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 5, 30, 7, 902473, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
