# Generated by Django 2.1.1 on 2018-09-17 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180917_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 17, 18, 18, 29, 677030, tzinfo=utc)),
        ),
    ]
