# Generated by Django 2.1.1 on 2018-09-26 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180926_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 18, 42, 35, 41942, tzinfo=utc)),
        ),
    ]
