# Generated by Django 2.1.1 on 2018-09-17 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180917_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 9, 17, 18, 21, 26, 475928, tzinfo=utc)),
        ),
    ]
