# Generated by Django 2.1.1 on 2018-10-27 10:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20181027_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rent_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_time_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 11, 54, 30, 665725, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 11, 54, 30, 665725, tzinfo=utc)),
        ),
    ]
