# Generated by Django 2.1.1 on 2018-09-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180917_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='desp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='start',
        ),
    ]
