# Generated by Django 2.1.1 on 2018-09-18 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180917_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=None, verbose_name=datetime.datetime(2018, 9, 18, 2, 55, 56, 944710, tzinfo=utc)),
        ),
    ]
