# Generated by Django 2.1.1 on 2018-09-27 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180927_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='start',
            new_name='timestart',
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 11, 47, 12, 522918, tzinfo=utc)),
        ),
    ]
