# Generated by Django 2.1.1 on 2018-09-27 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180927_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desp',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='timestart',
            new_name='time_start',
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 11, 49, 41, 532563, tzinfo=utc)),
        ),
    ]
