# Generated by Django 2.1.1 on 2018-09-18 02:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(default=None, verbose_name=datetime.datetime(2018, 9, 18, 2, 56, 3, 415721, tzinfo=utc)),
        ),
    ]
